### ISSUE TITLE
Duplicate instances for `MonadThrow` and `MonadCatch`

### ISSUE THREAD

**Issue by michaelt** [Gabriel439/Haskell-Pipes-Library#183]
As it stands the repositories for `pipes` and `pipes-safe` can't be compiled together. This was introduced with https://github.com/Gabriel439/Haskell-Pipes-Library/pull/180

    src/Pipes/Safe.hs:181:10: error:
        Duplicate instance declarations:
          instance MonadThrow m => MonadThrow (Proxy a' a b' b m)
            -- Defined at src/Pipes/Safe.hs:181:10
          instance MonadThrow m => MonadThrow (Proxy a' a b' b m)
            -- Defined in ‘Pipes.Internal’

    src/Pipes/Safe.hs:184:10: error:
        Duplicate instance declarations:
          instance MonadCatch m => MonadCatch (Proxy a' a b' b m)
            -- Defined at src/Pipes/Safe.hs:184:10
          instance MonadCatch m => MonadCatch (Proxy a' a b' b m)
            -- Defined in ‘Pipes.Internal’

**Comment by michaelt** [comment]
This means `pipes-text` and `pipes-network` also fail.

**Comment by Gabriel439** [comment]
Note that I haven't release this to Hackage, yet.  Wouldn't bumping the major number to 4.3 as part of this release avoid this problem?  `pipes-safe` currently has a `pipes < 4.3` constraint

**Comment by michaelt** [comment]
Okay, I see how you are ordering events, thanks. I didn't make it clear that there is no difficulty on hackage.    I have a script to build several github repositories together, which broke, and I wondered if the conflict had been noticed.  Of course, a version bump will mean the repositories don't build together for another reason.
